server:
  port: 10000

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  application:
    name: consumer
  # Consul配置
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: false
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp

#  ribbon:
#    # 每个操作都开启重试机制
#    OkToRetryOnAllOperations: false

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 10000
  SocketTimeout: 10000
  OkToRetryOnAllOperations: false
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  retryableStatusCodes: 404,502,500

# hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 120000